#!/usr/bin/env sh

set -eu

hook_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$hook_dir/lib/validate-conventional-commit.sh"

message_file=$1
subject=$(sed -n '/^[[:space:]]*#/d; /^[[:space:]]*$/d; {p; q;}' "$message_file")

validate_conventional_subject "$subject"
