// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'bun --bun prisma/seed.ts',
  },
  datasource: {
    url: 'postgresql://postgres:password@localhost:5433/eduflow_db?schema=public',
  },
});
