export const PLATFORM_PERMISSION = {
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_UPDATE: 'USERS_UPDATE',
  ROLES_VIEW: 'ROLES_VIEW',
  ROLES_MANAGE: 'ROLES_MANAGE',
  COURSES_CREATE: 'COURSES_CREATE',
  COURSES_VIEW_ALL: 'COURSES_VIEW_ALL',
  COURSES_MODERATE: 'COURSES_MODERATE',
  AI_USE_CHAT: 'AI_USE_CHAT',
  AI_USE_WRITING: 'AI_USE_WRITING',
  PERSONAL_FILES_MANAGE: 'PERSONAL_FILES_MANAGE',
  SYSTEM_SETTINGS_MANAGE: 'SYSTEM_SETTINGS_MANAGE',
} as const;

export const COURSE_PERMISSION = {
  COURSE_SETTINGS_MANAGE: 'COURSE_SETTINGS_MANAGE',
  COURSE_MEMBERS_VIEW: 'COURSE_MEMBERS_VIEW',
  COURSE_MEMBERS_MANAGE: 'COURSE_MEMBERS_MANAGE',
  COURSE_CONTENT_VIEW: 'COURSE_CONTENT_VIEW',
  COURSE_CONTENT_CREATE: 'COURSE_CONTENT_CREATE',
  COURSE_CONTENT_UPDATE: 'COURSE_CONTENT_UPDATE',
  COURSE_CONTENT_DELETE: 'COURSE_CONTENT_DELETE',
  ASSESSMENTS_VIEW: 'ASSESSMENTS_VIEW',
  ASSESSMENTS_CREATE: 'ASSESSMENTS_CREATE',
  ASSESSMENTS_UPDATE: 'ASSESSMENTS_UPDATE',
  ASSESSMENTS_DELETE: 'ASSESSMENTS_DELETE',
  ASSESSMENTS_RESULTS_VIEW: 'ASSESSMENTS_RESULTS_VIEW',
  ASSESSMENTS_GRADE: 'ASSESSMENTS_GRADE',
  COURSE_FILES_VIEW: 'COURSE_FILES_VIEW',
  COURSE_FILES_MANAGE: 'COURSE_FILES_MANAGE',
  AI_USE_COURSE_GENERATION: 'AI_USE_COURSE_GENERATION',
  COURSE_ANALYTICS_VIEW: 'COURSE_ANALYTICS_VIEW',
} as const;

export type PlatformPermissionKey =
  (typeof PLATFORM_PERMISSION)[keyof typeof PLATFORM_PERMISSION];

export type CoursePermissionKey =
  (typeof COURSE_PERMISSION)[keyof typeof COURSE_PERMISSION];

export type PermissionKey = PlatformPermissionKey | CoursePermissionKey;

export const PLATFORM_PERMISSION_KEYS = Object.values(PLATFORM_PERMISSION);

export const COURSE_PERMISSION_KEYS = Object.values(COURSE_PERMISSION);

export const PERMISSION_KEYS = [
  ...PLATFORM_PERMISSION_KEYS,
  ...COURSE_PERMISSION_KEYS,
] as PermissionKey[];

export function isCoursePermissionKey(key: string): key is CoursePermissionKey {
  return COURSE_PERMISSION_KEYS.includes(key as CoursePermissionKey);
}

export function isPlatformPermissionKey(
  key: string
): key is PlatformPermissionKey {
  return PLATFORM_PERMISSION_KEYS.includes(key as PlatformPermissionKey);
}
