type Translate = (
  key: string,
  values?: Record<string, string | number>
) => string;

const RANKING_CURRENT_TOKEN = '__GAME_QUIZ_CURRENT__';
const RANKING_TOTAL_TOKEN = '__GAME_QUIZ_TOTAL__';

export function formatGameQuizRankingProgress(
  template: string,
  current: number,
  total: number
) {
  return template
    .replace(RANKING_CURRENT_TOKEN, String(current))
    .replace(RANKING_TOTAL_TOKEN, String(total));
}

export function getGameQuizCopy(t: Translate) {
  return {
    common: {
      loading: t('common.loading'),
      retry: t('common.retry'),
      save: t('common.save'),
      saving: t('common.saving'),
      cancel: t('common.cancel'),
      back: t('common.back'),
      close: t('common.close'),
      error: t('common.error'),
      copied: t('common.copied'),
    },
    library: {
      title: t('library.title'),
      description: t('library.description'),
      create: t('library.create'),
      emptyTitle: t('library.emptyTitle'),
      emptyDescription: t('library.emptyDescription'),
      noQuestions: t('library.noQuestions'),
      questions: t('library.questions'),
      updated: t('library.updated'),
      edit: t('library.edit'),
      host: t('library.host'),
      liveRally: t('library.liveRally'),
    },
    editor: {
      template: t('editor.template'),
      title: t('editor.title'),
      description: t('editor.description'),
      details: t('editor.details'),
      titleLabel: t('editor.titleLabel'),
      topicLabel: t('editor.topicLabel'),
      difficultyLabel: t('editor.difficultyLabel'),
      question: t('editor.question'),
      prompt: t('editor.prompt'),
      hint: t('editor.hint'),
      explanation: t('editor.explanation'),
      timeLimit: t('editor.timeLimit'),
      maxPoints: t('editor.maxPoints'),
      seconds: t('editor.seconds'),
      answer: t('editor.answer'),
      correct: t('editor.correct'),
      addQuestion: t('editor.addQuestion'),
      removeQuestion: t('editor.removeQuestion'),
      addAnswer: t('editor.addAnswer'),
      removeAnswer: t('editor.removeAnswer'),
      settings: t('editor.settings'),
      randomizeQuestions: t('editor.randomizeQuestions'),
      randomizeAnswers: t('editor.randomizeAnswers'),
      preview: t('editor.preview'),
      host: t('editor.host'),
      saved: t('editor.saved'),
      conflict: t('editor.conflict'),
      create: t('editor.create'),
      validation: t('editor.validation'),
      draft: t('editor.draft'),
      easy: t('editor.easy'),
      medium: t('editor.medium'),
      hard: t('editor.hard'),
      allSaved: t('editor.allSaved'),
      duplicateQuestion: t('editor.duplicateQuestion'),
      estimatedDuration: t('editor.estimatedDuration'),
      learningDetails: t('editor.learningDetails'),
      markCorrect: t('editor.markCorrect'),
      moveDown: t('editor.moveDown'),
      moveUp: t('editor.moveUp'),
      rallyOverview: t('editor.rallyOverview'),
      totalPossiblePoints: t('editor.totalPossiblePoints'),
      unsavedChanges: t('editor.unsavedChanges'),
      unspecified: t('editor.unspecified'),
    },
    aiGenerate: {
      action: t('aiGenerate.action'),
      title: t('aiGenerate.title'),
      description: t('aiGenerate.description'),
      sourcesStep: t('aiGenerate.sourcesStep'),
      guidanceStep: t('aiGenerate.guidanceStep'),
      reviewStep: t('aiGenerate.reviewStep'),
      courseLabel: t('aiGenerate.courseLabel'),
      coursePlaceholder: t('aiGenerate.coursePlaceholder'),
      lessonsLabel: t('aiGenerate.lessonsLabel'),
      lessonsDescription: t('aiGenerate.lessonsDescription'),
      lessonsSelected: t('aiGenerate.lessonsSelected'),
      lessonSelectionLimit: t('aiGenerate.lessonSelectionLimit', { count: 20 }),
      noSourcesTitle: t('aiGenerate.noSourcesTitle'),
      noSourcesDescription: t('aiGenerate.noSourcesDescription'),
      noLessonsTitle: t('aiGenerate.noLessonsTitle'),
      noLessonsDescription: t('aiGenerate.noLessonsDescription'),
      sourceLoadErrorTitle: t('aiGenerate.sourceLoadErrorTitle'),
      sourceLoadErrorDescription: t('aiGenerate.sourceLoadErrorDescription'),
      questionCountLabel: t('aiGenerate.questionCountLabel'),
      questionCountDescription: t('aiGenerate.questionCountDescription'),
      additionalPromptLabel: t('aiGenerate.additionalPromptLabel'),
      additionalPromptPlaceholder: t('aiGenerate.additionalPromptPlaceholder'),
      additionalPromptDescription: t('aiGenerate.additionalPromptDescription'),
      generate: t('aiGenerate.generate'),
      generating: t('aiGenerate.generating'),
      generationErrorTitle: t('aiGenerate.generationErrorTitle'),
      generationErrorDescription: t('aiGenerate.generationErrorDescription'),
      reviewDescription: t('aiGenerate.reviewDescription'),
      correctAnswer: t('aiGenerate.correctAnswer'),
      previousQuestion: t('aiGenerate.previousQuestion'),
      nextQuestion: t('aiGenerate.nextQuestion'),
      reject: t('aiGenerate.reject'),
      accept: t('aiGenerate.accept'),
      continue: t('aiGenerate.continue'),
      capacityReached: t('aiGenerate.capacityReached'),
    },
    preview: {
      title: t('preview.title'),
      backToEditor: t('preview.backToEditor'),
      deviceView: t('preview.deviceView'),
      host: t('preview.host'),
      participant: t('preview.participant'),
      question: t('preview.question'),
      points: t('preview.points'),
      answerSelected: t('preview.answerSelected'),
      previous: t('preview.previous'),
      next: t('preview.next'),
      reveal: t('preview.reveal'),
      reset: t('preview.reset'),
      samplePlayer: t('preview.samplePlayer'),
    },
    host: {
      title: t('host.title'),
      joinCode: t('host.joinCode'),
      joinAt: t('host.joinAt'),
      joinedPlayers: t('host.joinedPlayers'),
      readyToStart: t('host.readyToStart'),
      shareLink: t('host.shareLink'),
      copyLink: t('host.copyLink'),
      openQrCode: t('host.openQrCode'),
      qrCodeDialogTitle: t('host.qrCodeDialogTitle'),
      players: t('host.players'),
      answers: t('host.answers'),
      answersCount: t('host.answersCount'),
      averageResponseTime: t('host.averageResponseTime'),
      correctRate: t('host.correctRate'),
      responses: t('host.responses'),
      questionStatistics: t('host.questionStatistics'),
      question: t('host.question'),
      joinOpen: t('host.joinOpen'),
      joinLocked: t('host.joinLocked'),
      lockJoining: t('host.lockJoining'),
      unlockJoining: t('host.unlockJoining'),
      moreRespondents: {
        one: t('host.moreRespondents', { count: 1 }),
        other: t('host.moreRespondents', { count: 2 }),
      },
      start: t('host.start'),
      skip: t('host.skip'),
      next: t('host.next'),
      scoreboard: t('host.scoreboard'),
      podium: t('host.podium'),
      endGame: t('host.endGame'),
      endGameConfirmTitle: t('host.endGameConfirmTitle'),
      endGameConfirmDescription: t('host.endGameConfirmDescription'),
      endSession: t('host.endSession'),
      viewReport: t('host.viewReport'),
      viewFullLeaderboard: t('host.viewFullLeaderboard'),
      fullLeaderboardTitle: t('host.fullLeaderboardTitle'),
      emptyLeaderboard: t('host.emptyLeaderboard'),
      congratulations: t('host.congratulations'),
      congratulationsDescription: t('host.congratulationsDescription'),
      lobby: t('host.lobby'),
      noPlayers: t('host.noPlayers'),
      online: t('host.online'),
      offline: t('host.offline'),
    },
    join: {
      title: t('join.title'),
      description: t('join.description'),
      codeLabel: t('join.codeLabel'),
      nameLabel: t('join.nameLabel'),
      nameRequired: t('join.nameRequired'),
      join: t('join.join'),
      joining: t('join.joining'),
      codeHint: t('join.codeHint'),
    },
    player: {
      waiting: t('player.waiting'),
      waitingDescription: t('player.waitingDescription'),
      submitted: t('player.submitted'),
      submittedDescription: t('player.submittedDescription'),
      reveal: t('player.reveal'),
      correct: t('player.correct'),
      notCorrect: t('player.notCorrect'),
      points: t('player.points'),
      pts: t('player.pts'),
      pin: t('player.pin'),
      hint: t('player.hint'),
      question: t('player.question'),
      finishTitle: t('player.finishTitle'),
      finishDescription: t('player.finishDescription'),
      score: t('player.score'),
      podium: t('player.podium'),
      rank: t('player.rank'),
      noPodium: t('player.noPodium'),
      leaderboard: t('player.leaderboard'),
      rankingProgress: t('player.rankingProgress', {
        current: RANKING_CURRENT_TOKEN,
        total: RANKING_TOTAL_TOKEN,
      }),
      you: t('player.you'),
      keepGoing: t('player.keepGoing'),
      waitingForNext: t('player.waitingForNext'),
      connection: t('player.connection'),
      hostEndedTitle: t('player.hostEndedTitle'),
      hostEndedDescription: t('player.hostEndedDescription'),
    },
    report: {
      title: t('report.title'),
      description: t('report.description'),
      players: t('report.players'),
      questions: t('report.questions'),
      responses: t('report.responses'),
      correct: t('report.correct'),
      averagePoints: t('report.averagePoints'),
      finalStandings: t('report.finalStandings'),
      noData: t('report.noData'),
    },
  } as const;
}

export type GameQuizCopy = ReturnType<typeof getGameQuizCopy>;

// Server pages always provide localized copy. This fallback keeps isolated UI tests deterministic.
export const gameQuizCopy = getGameQuizCopy((key, values) => {
  if (key === 'host.moreRespondents' && values) {
    return `more respondent${values.count === 1 ? '' : 's'}`;
  }

  return key;
});
