import { type NextRequest, NextResponse } from 'next/server';
import createMiddleware from 'next-intl/middleware';
import { routing } from '@/i18n/routing';
import { auth, type Session } from '@/lib/auth';
import { isPathMatched } from '@/utils/path-helper';
import { sanitizeUrl } from '@/utils/url-helper';
import { AUTH_PATHS, PUBLIC_PATHS } from './constants/common';

const intlMiddleware = createMiddleware(routing);

function hasActiveSession(sessionData: Session): boolean {
  const expiresAt = sessionData.session.expiresAt;

  const expiresAtTimestamp = new Date(expiresAt).getTime();
  if (Number.isNaN(expiresAtTimestamp)) return false;

  return expiresAtTimestamp > Date.now();
}

const handleRedirect = async ({
  req,
}: {
  req: NextRequest;
}): Promise<{
  res: NextResponse;
  redirect: boolean;
}> => {
  let hasSession = false;
  let userRole: string | null = null;
  const sessionData = await auth.api.getSession({ headers: req.headers });

  if (sessionData) {
    hasSession = hasActiveSession(sessionData);
    userRole = sessionData.user?.role;
  }

  const isApiPath = isPathMatched(req.nextUrl.pathname, ['/api']);
  const isRolePath = isPathMatched(req.nextUrl.pathname, ['/role']);
  const isAuthPath = isPathMatched(req.nextUrl.pathname, AUTH_PATHS);
  const isPublicPath = isPathMatched(req.nextUrl.pathname, PUBLIC_PATHS);
  const isProtectedPath = !isPublicPath && !isAuthPath;

  if (isApiPath) {
    return { res: NextResponse.next(), redirect: true };
  }

  if (hasSession && !userRole && !isRolePath && !isAuthPath) {
    const roleUrl = new URL('/role', req.nextUrl.origin);
    return { res: NextResponse.redirect(roleUrl), redirect: true };
  }

  if (hasSession && userRole && isRolePath) {
    const dashboardUrl = new URL('/', req.nextUrl.origin);
    return { res: NextResponse.redirect(dashboardUrl), redirect: true };
  }

  if (!hasSession && isProtectedPath) {
    const loginUrl = new URL('/login', req.nextUrl.origin);
    loginUrl.searchParams.set(
      'nextUrl',
      req.nextUrl.pathname + req.nextUrl.search
    );

    return { res: NextResponse.redirect(loginUrl), redirect: true };
  }

  if (hasSession && isAuthPath) {
    const nextUrl = req.nextUrl.searchParams.get('nextUrl');
    const sanitizedNextUrl = sanitizeUrl(nextUrl) || '/';
    const redirectUrl = new URL(sanitizedNextUrl, req.nextUrl.origin);

    return { res: NextResponse.redirect(redirectUrl), redirect: true };
  }

  const nextRes = NextResponse.next();

  return { res: nextRes, redirect: false };
};

export async function proxy(req: NextRequest) {
  // Handle special cases for public, authenticating paths
  const { res: nextRes, redirect } = await handleRedirect({ req });
  if (redirect) return nextRes;

  return intlMiddleware(req);
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - robots.txt (SEO)
     * - sitemap.xml (SEO)
     * - site.webmanifest (legacy PWA manifest)
     * - manifest.webmanifest (PWA manifest generated by Next.js)
     * - sw.js (service worker)
     * - monitoring (analytics)
     * - .well-known (domain verification files)
     * Excludes files with the following extensions for static assets:
     * - svg
     * - png
     * - jpg
     * - jpeg
     * - mp3
     * - wav
     * - ogg
     * - m4a
     * - pdf
     * - gif
     * - webp
     */

    '/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|site.webmanifest|manifest.webmanifest|sw.js|serwist|monitoring|\\.well-known|.*\\.(?:svg|png|jpg|jpeg|mp3|wav|ogg|m4a|pdf|gif|webp)$).*)',
  ],
};
