import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import createMiddleware from 'next-intl/middleware';
import { routing } from './i18n/routing';

const intlMiddleware = createMiddleware(routing);

export default async function middleware(req: NextRequest) {
  if (req.nextUrl.pathname.startsWith('/api')) {
    return NextResponse.next();
  }

  // Check for better-auth session token
  const hasSession = req.cookies.has('better-auth.session_token') || req.cookies.has('__Secure-better-auth.session_token');

  const isDashboard = req.nextUrl.pathname.includes('/dashboard');
  const isLogin = req.nextUrl.pathname.includes('/login');

  if (!hasSession && isDashboard) {
    const newUrl = new URL('/login', req.nextUrl.origin);
    return NextResponse.redirect(newUrl);
  }

  if (hasSession && isLogin) {
    return NextResponse.redirect(new URL('/dashboard', req.nextUrl.origin));
  }

  return intlMiddleware(req);
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - robots.txt (SEO)
     * - sitemap.xml (SEO)
     * - site.webmanifest (legacy PWA manifest)
     * - manifest.webmanifest (PWA manifest generated by Next.js)
     * - sw.js (service worker)
     * - monitoring (analytics)
     * - .well-known (domain verification files)
     * Excludes files with the following extensions for static assets:
     * - svg
     * - png
     * - jpg
     * - jpeg
     * - mp3
     * - wav
     * - ogg
     * - m4a
     * - pdf
     * - gif
     * - webp
     */

    '/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|site.webmanifest|manifest.webmanifest|sw.js|serwist|monitoring|\\.well-known|.*\\.(?:svg|png|jpg|jpeg|mp3|wav|ogg|m4a|pdf|gif|webp)$).*)',
  ],
};
