import {
  COURSE_PERMISSION,
  COURSE_PERMISSION_KEYS,
  type CoursePermissionKey,
  PLATFORM_PERMISSION,
  PLATFORM_PERMISSION_KEYS,
  type PlatformPermissionKey,
} from '../../../src/lib/permissions/permission-keys';
import type { CourseRoleName, PlatformRoleName } from '../role/types';

export const PLATFORM_ROLE_PERMISSION_DEFAULTS: Record<
  PlatformRoleName,
  PlatformPermissionKey[]
> = {
  ADMIN: PLATFORM_PERMISSION_KEYS,
  TEACHER: [
    PLATFORM_PERMISSION.COURSES_VIEW,
    PLATFORM_PERMISSION.COURSES_MANAGE,
    PLATFORM_PERMISSION.AI_USE_CHAT,
    PLATFORM_PERMISSION.AI_USE_WRITING,
    PLATFORM_PERMISSION.AI_USE_SOCRATIC,
    PLATFORM_PERMISSION.AI_USE_STUDY,
    PLATFORM_PERMISSION.PERSONAL_FILES_MANAGE,
  ],
  STUDENT: [
    PLATFORM_PERMISSION.AI_USE_CHAT,
    PLATFORM_PERMISSION.AI_USE_WRITING,
    PLATFORM_PERMISSION.AI_USE_SOCRATIC,
    PLATFORM_PERMISSION.AI_USE_STUDY,
    PLATFORM_PERMISSION.PERSONAL_FILES_MANAGE,
  ],
};

export const COURSE_ROLE_PERMISSION_DEFAULTS: Record<
  CourseRoleName,
  CoursePermissionKey[]
> = {
  COURSE_OWNER: COURSE_PERMISSION_KEYS,
  TEACHER: [
    COURSE_PERMISSION.COURSE_ROLES_MANAGE,
    COURSE_PERMISSION.COURSE_MEMBERS_VIEW,
    COURSE_PERMISSION.COURSE_CONTENT_VIEW,
    COURSE_PERMISSION.COURSE_CONTENT_CREATE,
    COURSE_PERMISSION.COURSE_CONTENT_UPDATE,
    COURSE_PERMISSION.ASSESSMENTS_VIEW,
    COURSE_PERMISSION.ASSESSMENTS_CREATE,
    COURSE_PERMISSION.ASSESSMENTS_UPDATE,
    COURSE_PERMISSION.ASSESSMENTS_RESULTS_VIEW,
    COURSE_PERMISSION.ASSESSMENTS_GRADE,
    COURSE_PERMISSION.COURSE_FILES_VIEW,
    COURSE_PERMISSION.COURSE_FILES_MANAGE,
    COURSE_PERMISSION.AI_USE_COURSE_GENERATION,
    COURSE_PERMISSION.COURSE_ANALYTICS_VIEW,
  ],
  STUDENT: [
    COURSE_PERMISSION.COURSE_CONTENT_VIEW,
    COURSE_PERMISSION.ASSESSMENTS_VIEW,
    COURSE_PERMISSION.ASSESSMENTS_RESULTS_VIEW,
    COURSE_PERMISSION.COURSE_FILES_VIEW,
  ],
};

export { COURSE_PERMISSION_KEYS, PLATFORM_PERMISSION_KEYS };
